from pathlib import Path

p = Path('/home/ubuntu/onchain-queue-dashboard/client/src/contexts/LanguageContext.tsx')
s = p.read_text()
common = ' resetSettings: "Reset to defaults", nextRefresh: "Next refresh in {seconds}s", refreshPaused: "Auto-refresh paused while this tab is inactive", blockUpdated: "Block {block}", onchainReadError: "Could not read on-chain data", checkContractAndAbi: "Check the Contract address, ABI, and network.", walletNotFound: "No compatible wallet found", walletConnected: "Wallet connected", walletConnectFailed: "Wallet connection failed", signingIn: "Creating nonce and waiting for signature", signInSuccess: "Wallet sign-in confirmed", signInFailed: "Wallet sign-in failed", registrationPreparing: "Preparing referral registration", registrationConfirmed: "Referral registration confirmed", registrationFailed: "Referral registration failed", ownerWalletReady: "Owner wallet ready", ownerConnectFailed: "Could not connect Owner wallet", mappingVerified: "Mapping matches the chain", mappingMismatch: "Mapping does not match the chain", verifyFailed: "On-chain verification failed", disablePreparing: "Preparing on-chain disable", disableConfirmed: "Referral Code disabled on-chain", disableFailed: "Could not disable Referral Code", transactionRejected: "Transaction was rejected or reverted", tabInactive: "Tab inactive",'
marker = 'changedCount: "{count} referral mapping(s) changed on-chain",'
s = s.replace(marker, marker + common, 1)
locales = {
'de': ' resetSettings: "Auf Standard zurücksetzen", nextRefresh: "Nächste Aktualisierung in {seconds}s", refreshPaused: "Automatische Aktualisierung pausiert, weil dieser Tab inaktiv ist", blockUpdated: "Block {block}", onchainReadError: "On-Chain-Daten konnten nicht gelesen werden", checkContractAndAbi: "Contract-Adresse, ABI und Netzwerk prüfen.", walletNotFound: "Keine kompatible Wallet gefunden", walletConnected: "Wallet verbunden", walletConnectFailed: "Wallet-Verbindung fehlgeschlagen", signingIn: "Nonce wird erstellt, Signatur wird erwartet", signInSuccess: "Wallet-Anmeldung bestätigt", signInFailed: "Wallet-Anmeldung fehlgeschlagen", registrationPreparing: "Referral-Registrierung wird vorbereitet", registrationConfirmed: "Referral-Registrierung bestätigt", registrationFailed: "Referral-Registrierung fehlgeschlagen", ownerWalletReady: "Eigentümer-Wallet bereit", ownerConnectFailed: "Eigentümer-Wallet konnte nicht verbunden werden", mappingVerified: "Mapping stimmt mit der Chain überein", mappingMismatch: "Mapping stimmt nicht mit der Chain überein", verifyFailed: "On-Chain-Prüfung fehlgeschlagen", disablePreparing: "On-Chain-Deaktivierung wird vorbereitet", disableConfirmed: "Referral-Code auf der Chain deaktiviert", disableFailed: "Referral-Code konnte nicht deaktiviert werden", transactionRejected: "Transaktion abgelehnt oder zurückgesetzt", tabInactive: "Tab inaktiv",',
'zh': ' resetSettings: "恢复默认设置", nextRefresh: "下次刷新将在 {seconds} 秒后进行", refreshPaused: "标签页未激活，自动刷新已暂停", blockUpdated: "区块 {block}", onchainReadError: "无法读取链上数据", checkContractAndAbi: "请检查合约地址、ABI 和网络。", walletNotFound: "未找到兼容的钱包", walletConnected: "钱包已连接", walletConnectFailed: "钱包连接失败", signingIn: "正在创建 nonce 并等待签名", signInSuccess: "钱包登录已确认", signInFailed: "钱包登录失败", registrationPreparing: "正在准备推荐注册", registrationConfirmed: "推荐注册已确认", registrationFailed: "推荐注册失败", ownerWalletReady: "所有者钱包已准备好", ownerConnectFailed: "无法连接所有者钱包", mappingVerified: "映射与链上数据一致", mappingMismatch: "映射与链上数据不一致", verifyFailed: "链上验证失败", disablePreparing: "正在准备链上禁用", disableConfirmed: "推荐码已在链上禁用", disableFailed: "无法禁用推荐码", transactionRejected: "交易被拒绝或回滚", tabInactive: "标签页未激活",',
'lo': ' resetSettings: "ຄືນຄ່າເລີ່ມຕົ້ນ", nextRefresh: "ຣີເຟຣຊຄັ້ງຕໍ່ໄປໃນ {seconds} ວິນາທີ", refreshPaused: "ຢຸດ Auto-refresh ເພາະ Tab ບໍ່ໄດ້ໃຊ້ງານ", blockUpdated: "Block {block}", onchainReadError: "ອ່ານຂໍ້ມູນ On-chain ບໍ່ສຳເລັດ", checkContractAndAbi: "ກວດ Contract address, ABI ແລະ network.", walletNotFound: "ບໍ່ພົບ Wallet ທີ່ຮອງຮັບ", walletConnected: "ເຊື່ອມຕໍ່ Wallet ແລ້ວ", walletConnectFailed: "ເຊື່ອມຕໍ່ Wallet ບໍ່ສຳເລັດ", signingIn: "ກຳລັງສ້າງ nonce ແລະລໍຖ້າການເຊັນ", signInSuccess: "ຢືນຢັນການເຂົ້າໃຊ້ Wallet ແລ້ວ", signInFailed: "ເຂົ້າໃຊ້ Wallet ບໍ່ສຳເລັດ", registrationPreparing: "ກຳລັງກຽມລົງທະບຽນ Referral", registrationConfirmed: "ຢືນຢັນການລົງທະບຽນ Referral ແລ້ວ", registrationFailed: "ລົງທະບຽນ Referral ບໍ່ສຳເລັດ", ownerWalletReady: "Owner Wallet ພ້ອມໃຊ້ງານ", ownerConnectFailed: "ເຊື່ອມຕໍ່ Owner Wallet ບໍ່ສຳເລັດ", mappingVerified: "Mapping ກົງກັບ On-chain", mappingMismatch: "Mapping ບໍ່ກົງກັບ On-chain", verifyFailed: "ກວດສອບ On-chain ບໍ່ສຳເລັດ", disablePreparing: "ກຳລັງກຽມປິດໃຊ້ On-chain", disableConfirmed: "ປິດ Referral Code ໃນ On-chain ແລ້ວ", disableFailed: "ປິດ Referral Code ບໍ່ສຳເລັດ", transactionRejected: "Transaction ຖືກປະຕິເສດ ຫຼື revert", tabInactive: "Tab ບໍ່ໄດ້ໃຊ້ງານ",',
'th': ' resetSettings: "รีเซ็ตเป็นค่าเริ่มต้น", nextRefresh: "จะรีเฟรชอีกครั้งใน {seconds} วินาที", refreshPaused: "หยุด Auto-refresh ชั่วคราวเพราะแท็บไม่ active", blockUpdated: "Block {block}", onchainReadError: "อ่านข้อมูล On-chain ไม่สำเร็จ", checkContractAndAbi: "ตรวจสอบ Contract Address, ABI และเครือข่าย", walletNotFound: "ไม่พบกระเป๋าที่รองรับ", walletConnected: "เชื่อมต่อกระเป๋าแล้ว", walletConnectFailed: "เชื่อมต่อกระเป๋าไม่สำเร็จ", signingIn: "กำลังสร้าง nonce และรอการเซ็นข้อความ", signInSuccess: "ยืนยันการเข้าสู่ระบบด้วย Wallet แล้ว", signInFailed: "เข้าสู่ระบบด้วย Wallet ไม่สำเร็จ", registrationPreparing: "กำลังเตรียมลงทะเบียน Referral", registrationConfirmed: "ยืนยันการลงทะเบียน Referral แล้ว", registrationFailed: "ลงทะเบียน Referral ไม่สำเร็จ", ownerWalletReady: "Owner Wallet พร้อมใช้งาน", ownerConnectFailed: "เชื่อมต่อ Owner Wallet ไม่สำเร็จ", mappingVerified: "Mapping ตรงกับเชน", mappingMismatch: "Mapping ไม่ตรงกับเชน", verifyFailed: "ตรวจสอบ On-chain ไม่สำเร็จ", disablePreparing: "กำลังเตรียมปิด Referral Code บนเชน", disableConfirmed: "ปิด Referral Code บนเชนแล้ว", disableFailed: "ปิด Referral Code ไม่สำเร็จ", transactionRejected: "ธุรกรรมถูกยกเลิกหรือ Contract ปฏิเสธ", tabInactive: "แท็บไม่ active",',
}
for locale, additions in locales.items():
    lines = s.splitlines(True)
    for i, line in enumerate(lines):
        if line.startswith(f'  {locale}:'):
            pos = line.rfind(' },')
            if pos < 0: raise SystemExit(f'cannot locate end of {locale}')
            lines[i] = line[:pos] + additions + line[pos:]
            break
    else: raise SystemExit(f'locale {locale} not found')
    s = ''.join(lines)
p.write_text(s)
